#!/bin/bash

# Request sudo access for the entire script
sudo echo "This script requires sudo access"

# Run the Kubernetes installer for the master node
wget "https://raw.githubusercontent.com/vickdini/CloudComputing/main/K8S+Docker_Master_Setup.sh"
chmod +x "K8S+Docker_Master_Setup.sh"
./K8S+Docker_Master_Setup.sh

# Install Rancher
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher

ip a
echo "Open the browser to the IP address (port 80)"
echo "Enter the password that you get by replacing the docker container ID in this command:"
echo "docker logs containerID  2>&1 | grep "Bootstrap Password:""
